import Link from 'next/link';
import { notFound } from 'next/navigation';
import { opportunity, requirements, documents, users } from '../../../persistence/repository';
import { categories, departments, statuses } from '../../../domain/requirements';
import { upload, review } from '../../actions';
export default async function Detail({params,searchParams}: {params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}) {
  const {id} = await params; const {error} = await searchParams; const item = opportunity(id); if (!item) notFound();
  const checklist = requirements(id), sources = documents(id), colleagues = users();
  return <><Link href="/opportunities">← All opportunities</Link><h1>{item.title}</h1><p>{item.funder_name} · {item.status} · Application due: {item.due_date || 'Not set'}</p>{error && <p role="alert" className="error">{error}</p>}
    <section className="panel"><h2>Upload application or guidelines</h2><p className="notice"><strong>Mock extraction:</strong> uploads are stored, but not read. Every upload produces three synthetic examples. Their excerpts are sample language, not verified quotations from your file. Review these only to explore the workflow.</p><form action={upload.bind(null,id)}><label>Source document (PDF, DOCX or TXT; up to 10 MB)<input type="file" name="document" accept=".pdf,.docx,.txt" required /></label><button>Upload & create sample suggestions</button></form></section>
    <h2>Source documents</h2>{sources.length ? <ul>{sources.map(d=><li key={d.id}><a href={`/documents/${d.id}`}>{d.filename}</a> · {d.parser}</li>)}</ul> : <p>No documents uploaded yet.</p>}
    <h2>Application checklist</h2><p>{checklist.filter(r=>r.review_state==='Proposed').length} awaiting review · {checklist.filter(r=>['Accepted','Edited'].includes(r.review_state)).length} human-confirmed · {checklist.filter(r=>r.review_state==='Rejected').length} rejected</p><p>Review decisions and work status are separate. “Save edits & confirm” records your corrected interpretation. Rejected items are retained for traceability.</p>
    {!checklist.length && <p>Upload a document to see sample requirements.</p>}
    {checklist.map(r=>{ const source = sources.find(d=>d.id===r.source_document_id); return <article className="panel" key={r.id}><div className="row"><h3>{r.text}</h3><span className={`badge ${r.review_state.toLowerCase()}`}>{r.review_state}</span></div><p>{r.category} · Suggested: {r.suggested_department} · Assigned department: {r.department}</p><p>Owner: {colleagues.find(u=>u.id===r.owner_id)?.name || 'Unassigned'} · Due: {r.due_date || 'Not set'} · Work status: {r.status}</p>
      <aside className="provenance"><strong>Source traceability — synthetic example</strong><p><a href={`/documents/${r.source_document_id}`}>{source?.filename}</a> · Document ID: <code>{r.source_document_id}</code></p><p>{r.source_page ? `Page ${r.source_page}` : 'Page unavailable'} · {r.source_section || 'Section unavailable'} · Confidence: {r.confidence === null ? 'Not scored (mock)' : `${Math.round(r.confidence*100)}%`}</p><blockquote>{r.source_excerpt}</blockquote></aside>
      <form action={review.bind(null,id,r.id)} className="row"><button name="action" value="accept">Accept current requirement</button><button className="secondary" name="action" value="reject">Reject</button></form>
      <details><summary>Edit, route & confirm</summary><form action={review.bind(null,id,r.id)} className="grid"><label className="wide">Requirement text<textarea name="text" defaultValue={r.text} required maxLength={2000}/></label><label>Category<select name="category" defaultValue={r.category}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Department<select name="department" defaultValue={r.department}>{departments.map(d=><option key={d}>{d}</option>)}</select></label><label>Owner<select name="owner" defaultValue={r.owner_id || ''}><option value="">Unassigned</option>{colleagues.map(u=><option key={u.id} value={u.id}>{u.name} ({u.department})</option>)}</select></label><label>Due date<input type="date" name="due_date" defaultValue={r.due_date || ''}/></label><label>Work status<select name="status" defaultValue={r.status}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="wide">Notes<textarea name="notes" defaultValue={r.notes} maxLength={4000}/></label><button name="action" value="edit">Save edits & confirm</button></form></details><details><summary>Original parser suggestion</summary><pre>{JSON.stringify(JSON.parse(r.original_suggestion),null,2)}</pre></details>{r.reviewed_at && <small>Last reviewed by demo user Alex Morgan at {r.reviewed_at}</small>}</article>;})}
  </>;
}
